### PR TITLE
animate transform vs left

### PR DESCRIPTION
**Pull request by alisa17**
Changing left for transform to try and improve performance: 
Screen Shot 2021-09-07 at 11 05 36 am

### CODE REVIEW

**Comment by michaelwebb76** [comment]
Ping @alisa17 @klaftertief @lrworth

**Review by klaftertief — COMMENTED** [review]
It's cool to not transition the position of the element.

But is there a nice way to not have the fractional percentage values? I'm not saying that the percentage should just be rounded, but that it should depend on the width of the containing block and not on the combined with of all the slides. I'm not seeing issues in the simple demo, but there might be glitches from rounding errors in other situations.

If this is not feasible I'm ok with the change.

**Comment by michaelwebb76** [comment]
@alisa17 ?

**Comment by michaelwebb76** [comment]
@alisa17 Coming up on a year that this has been open, it'd be _real nice_ if we could close it off

**Pull request merged**
